import { cl, isMain, trim, equal, compare, isEmpty } from '../src/index.js'
import Test from '../src/test.js'
import valid from '../src/validation.js'

const t = new Test()
t.true(valid.required('hoge'))
t.true(valid.required(1))
t.true(valid.required(0))
t.false(valid.required(''))
t.false(valid.required(null))
t.true(valid.min('hoge', 4))
t.false(valid.min('hog', 4))
t.true(valid.zenkaku('あいうえお　カキクケコ'))
t.false(valid.zenkaku('ｶｷｸｹｺ'))
t.true(valid.hanKatakana('ｶｷｸｹｺ'))
t.true(valid.email('hoge@hoge.com'))
t.false(valid.email('.hoge@hoge.com'))
t.false(valid.email('ho..ge@hoge.com'))
t.false(valid.email('hoge.@hoge.com'))
t.true(valid.url('http://hoge.com/index?hoge=hoge%20fuga+hoge&fuga=FUGA#hoge'))
t.true(valid.time('00:00:00'))
t.true(valid.time('23:59:59'))
t.false(valid.time('24:00:00'))
t.true(valid.date('2022-01-02'))
t.false(valid.date('2003-02-29'))
t.true(valid.date('2004-02-29'))
t.true(valid.datetime('2004-02-29 00:11:22'))
t.false(valid.password('hoge'))
t.false(valid.password('Hoge'))
t.false(valid.password('Hoge9'))
t.true(valid.password('Hoge9!'))
