import { trim, equal, compare, isEmpty } from '../src/index.js'
import Test from '../src/test.js'
import valid from '../src/validation.js'

const t = new Test()
const v = valid

t.true(v.required('hoge'))
t.true(v.required(1))
t.true(v.required(0))
t.false(v.required(''))
t.false(v.required(null))
t.true(v.number('123'))
t.false(v.number('a123'))
t.true(v.integer('-123'))
t.false(v.integer('12.3'))

t.true(v.min('hoge', 4))
t.false(v.min('hog', 4))
t.true(v.max('hoge', 4))
t.false(v.max('hoge!', 4))
t.true(v.compare(10, '>', 5))
t.true(v.compare('10', '==', 10))

t.true(v.zenkaku('あいうえお　カキクケコ'))
t.false(v.zenkaku('ｶｷｸｹｺ'))
t.false(v.zenkaku('abc'))
t.true(v.hanKatakana('ｶｷｸｹｺ'))
t.true(v.hiragana('あいうえお'))
t.false(v.hiragana('アイウエオ'))
t.true(v.katakana('アイウエオ'))
t.true(v.alphanum('abc123'))

t.true(v.email('hoge@hoge.com'))
t.false(v.email('.hoge@hoge.com'))
t.false(v.email('ho..ge@hoge.com'))
t.false(v.email('hoge.@hoge.com'))
t.true(v.url('http://hoge.com/index?hoge=hoge%20fuga+hoge&fuga=FUGA#hoge'))
t.true(v.ip('127.0.0.1'))
t.true(v.ip('255.255.255.255'))
t.false(v.ip('256.0.0.1'))

t.true(v.date('2022-01-02'))
t.true(v.date('2022/12/31'))
t.false(v.date('2003-02-29'))
t.true(v.date('2004-02-29'))
t.false(v.date('2022-13-01'))
t.true(v.time('00:00:00'))
t.true(v.time('23:59:59'))
t.false(v.time('24:00:00'))
t.false(v.time('12:60:00'))
t.true(v.hourmin('12:59'))
t.false(v.hourmin('12:60'))
t.true(v.datetime('2004-02-29 00:11:22'))

t.false(v.password('hoge'))
t.false(v.password('Hoge'))
t.false(v.password('Hoge9'))
t.true(v.password('Hoge9!'))
t.true(v.confirm('pw123')('pw123'))
t.false(v.confirm('pw123')('pw124'))
t.true(v.inList(1, [1, 2, 3]))
t.false(v.inList(4, [1, 2, 3]))
t.true(v.boolean('true'))
t.true(v.boolean(1))
t.false(v.boolean('yes'))
t.true(v.json('{"a":1}'))
t.false(v.json('{a:1}'))
